name: "translate"
backend: "python"
default_model_filename: "translate.py"
max_batch_size: 16

input [
  {
    name: "INPUT_TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "TRANSLATED_TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_CPU }]
dynamic_batching { }